# Generated by Django 3.2.9 on 2022-06-10 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectOnDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_1', models.CharField(max_length=50)),
                ('variable_2', models.TextField()),
                ('variable_4', models.DateTimeField(auto_now_add=True)),
                ('variable_5', models.DateTimeField(auto_now=True)),
                ('variable_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
